language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
matrix:
  include:
    - php: 7.0
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=highest
before_script:
  - composer self-update -q
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
script:
  # Setting stty prevents warning on lowest dependencies: https://github.com/sebastianbergmann/phpunit/issues/1976
  - stty cols 80; vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover
  - vendor/bin/phpcs src/ --standard=psr2 -sp
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
